lane :test do
  teams_url = "https://outlook.office.com/webhook/..."
  teams(
    title: "Fastlane says hello",
    message: "App successfully released!",
     facts:[
      {
        "name"=>"Platform",
        "value"=>"Android"
      },
      {
        "name"=>"Lane",
        "value"=>"android internal"
      }
    ],
    teams_url: teams_url
  )
end
